apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guardrail-api
  namespace: guardrail
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: guardrail.localtest.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guardrail-api
                port:
                  number: 80
