apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guardrail
resources:
  - namespace.yaml
  - configmap-rules.yaml
  - secret-api-key.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdb.yaml
  - hpa.yaml
