apiVersion: v1
kind: Service
metadata:
  name: guardrail-api
  namespace: guardrail
  labels:
    app: guardrail-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: guardrail-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
