apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guardrail.fullname" . }}
  labels:
    {{- include "guardrail.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "guardrail.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "guardrail.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/path: /metrics
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "guardrail.fullname" . }}
            - secretRef:
                name: {{ include "guardrail.fullname" . }}-env
{{- with .Values.pod.extraVolumeMounts }}
          volumeMounts:
{{ toYaml . | indent 12 }}
{{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- with .Values.pod.extraVolumes }}
      volumes:
{{ toYaml . | indent 8 }}
{{- end }}
