apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-guardrail-api.fullname" . }}-rules
  labels:
    {{- include "llm-guardrail-api.labels" . | nindent 4 }}
data:
  rules.yaml: |
{{ .Values.rules.inline | indent 4 }}
