{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "llm-guardrail-api.fullname" . }}
  labels:
    {{- include "llm-guardrail-api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "llm-guardrail-api.fullname" . }}
{{- end }}
