apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-guardrail-api.fullname" . }}-secrets
  labels:
    {{- include "llm-guardrail-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEY: {{ .Values.env.API_KEY | quote }}
