apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-guardrail-api.fullname" . }}
  labels:
    {{- include "llm-guardrail-api.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.targetPort }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "llm-guardrail-api.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
